config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :accounts do
    resources :transactions
  end

  root to: 'accounts#index'
end

app/models/account.rb
class Account < ApplicationRecord
  has_many :transactions

  before_save :audit_balance

  enum account_type: [:chequing, :creditline]

  def audit_balance
    self.balance = transactions.all.sum(:amount)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :account

  after_save :update_account_balance

  def update_account_balance
    self.account.save!    
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :accounts
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authenticate_user!

  def index
    @accounts = current_user.accounts
  end

  def show
    @account = current_user.accounts.find(params[:id])
  end

  def new
    @account = current_user.accounts.new
  end

  def create
    @account = current_user.accounts.new(account_params)
    respond_to do |format|
      if @account.save!
        format.html { redirect_to accounts_path, notice: "Successfully opened new #{@account.account_type} account." }
      else
        format.html { redirect_to new_accounts_path }
      end
    end
  end

  def destroy
  end

  private

  def account_params
    params.required(:account).permit(:account_type)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def index
  end

  def new
    @account = Account.find(params[:account_id])
    @transaction = @account.transactions.new
  end

  def create
  end

  def show
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/accounts/_form.html.erb
<%= form_for @account, :html => { :class => "form-horizontal" } do |f| %>
<% if @account.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(@account.errors.count, "error") %>
        The following prevented this account from being created:</h2>

    <ul>
        <% @account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
</div>
<% end %>

<div class="form-group">
    <label class="col-sm-3 control-label">Account Type:
    </label>
    <div class="col-sm-9">
        <%= f.select :account_type, Account.account_types.map { |w| [w[0].humanize, w[0]] } %>
    </div>
</div>

<div class="form-group">
    <label class="col-sm-3 control-label">
    </label>
    <div class="col-sm-9">
        <%= f.submit %>
    </div>
</div>
<% end %>

app/views/accounts/index.html.erb
<div class="row">
  <div class="col-md-offset-6 col-md-2"><%= link_to 'Open a New Account', new_account_path, class: 'btn btn-default' %></div>
</div>

<div class="row">
    <div class="col-md-8">
        <h1>Accounts</h1>

        <table class="table table-striped">
            <tr>
                <th>Account Type</th>
                <th>Account Number</th>
                <th>Balance</th>
            </tr>

            <% @accounts.each do |account| %>
            <tr>
                <td><%= account.account_type %></td>
                <td><%= account.id %></td>
                <td><%= account.balance %></td>
            </tr>
            <% end %>
        </table>
    </div>
</div>

app/views/accounts/new.html.erb
<div class="row">
    <div class="col-md-8">
        <h1>Open a New Account</h1>
        <%= render 'form' %>
    </div>
</div>

app/views/accounts/show.html.erb
<h1>Accounts#show</h1>
<p>Find me in app/views/accounts/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Imaginary Bank</title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <%= link_to 'Imaginary Bank', root_path, class: "navbar-brand" %>
                </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li><%= link_to 'Balances' %></li>
                        <li><%= link_to 'Transfer' %></li>
                        <li><%= link_to 'Settings' %></li>
                        <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
                    </ul>
                </div>

            </div>
        </nav>

        <div class="container-fluid">
            <% if notice %>
            <div class="alert alert-success alert-dismissible" role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
              <%= notice %>
            </div>
            <% end %>
            <% if alert  %>
            <div class="alert alert-danger alert-dismissible" role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
              <%= alert %>
            </div>
            <% end %>
            <%= yield %>
        </div>

    </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	  	<meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Imaginary Bank of the Internet</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>

    <style>
      body {
        padding-top: 40px;
        padding-bottom: 40px;
        background-color: #eee;
      }
    </style>

  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/transactions/index.html.erb
<h1>Transactions#index</h1>
<p>Find me in app/views/transactions/index.html.erb</p>

app/views/transactions/new.html.erb
<h1>Transactions#new</h1>
<p>Find me in app/views/transactions/new.html.erb</p>

app/views/transactions/show.html.erb
<h1>Transactions#show</h1>
<p>Find me in app/views/transactions/show.html.erb</p>